Bugfix to SKOPOS env var failing to properly set because BASH_SCRIPTS env var was not properly setting.

diff --git a/.bash/skopos/skopos.init b/.bash/skopos/skopos.init
--- a/.bash/skopos/skopos.init
+++ b/.bash/skopos/skopos.init
@@ -1,6 +1,12 @@
 #!/bin/bash
 
-export SKOPOS=$BASH_SCRIPTS/skopos/skopos.bash
+if [[ -n $BASH_SCRIPTS ]]; then
+  SKOPOS=$BASH_SCRIPTS/skopos/skopos.bash
+  export SKOPOS
+else
+  echo >&2 'Cannot set up skopos environment. $BASH_SCRIPTS env var is not set.'
+  exit 10
+fi
 
 # Begin Kraken env functions install_skopos
 # test
