Run shfmt over changed files

diff --git a/.bash/skopos/skopos.init b/.bash/skopos/skopos.init
--- a/.bash/skopos/skopos.init
+++ b/.bash/skopos/skopos.init
@@ -1,19 +1,19 @@
 #!/bin/bash
 
 if [[ -n $BASH_SCRIPTS ]]; then
-  SKOPOS=$BASH_SCRIPTS/skopos/skopos.bash
-  export SKOPOS
+	SKOPOS=$BASH_SCRIPTS/skopos/skopos.bash
+	export SKOPOS
 else
-  echo >&2 'Cannot set up skopos environment. $BASH_SCRIPTS env var is not set.'
-  exit 10
+	echo >&2 'Cannot set up skopos environment. $BASH_SCRIPTS env var is not set.'
+	exit 10
 fi
 
 # Begin Kraken env functions install_skopos
 # test
 if [[ -e $SKOPOS ]]; then
-  echo "Setting up kraken environment"
+	echo "Setting up kraken environment"
 
-  source "$SKOPOS"
-  alias sk="\$HOME/bin/skopos"
-  setup_cluster_env
+	source "$SKOPOS"
+	alias sk="\$HOME/bin/skopos"
+	setup_cluster_env
 fi
diff --git a/install b/install
--- a/install
+++ b/install
@@ -5,31 +5,31 @@ INSTALLED_STR="installed_skopos"
 BASH_SCRIPTS=$HOME/.bash
 
 if mkdir -p "$BASH_SCRIPTS" 2>/dev/null; then
-  if ! cp -avp .bash/ "$BASH_SCRIPTS"; then
-    echo >&2 "Unable to copy files to $BASH_SCRIPTS"
-    exit 8
-  fi
+	if ! cp -avp .bash/ "$BASH_SCRIPTS"; then
+		echo >&2 "Unable to copy files to $BASH_SCRIPTS"
+		exit 8
+	fi
 fi
 
 # this mkdir will not clobber
 if mkdir -p "$HOME/bin" 2>/dev/null; then
-  # This cp will not clobber any
-  # existing files without explicit
-  # permission.
-  if cp -iavp bin/* "$HOME/bin"; then
-    echo "Files installed successfully..."
+	# This cp will not clobber any
+	# existing files without explicit
+	# permission.
+	if cp -iavp bin/* "$HOME/bin"; then
+		echo "Files installed successfully..."
 
-  else
-    echo >&2 "Installation didn't fully succeed, but things might still be OK."
-    exit 2
-  fi
+	else
+		echo >&2 "Installation didn't fully succeed, but things might still be OK."
+		exit 2
+	fi
 else
-  echo >&2 "Unable to mkdir $HOME/bin. RC was $?"
-  exit 4
+	echo >&2 "Unable to mkdir $HOME/bin. RC was $?"
+	exit 4
 fi
 
 if [[ $(grep -c "$INSTALLED_STR" "$BASHRC") == 0 ]]; then
-  cat <<E >>"$BASHRC"
+	cat <<E >>"$BASHRC"
 
 ## $INSTALLED_STR
 BASH_SCRIPTS=$HOME/.bash
@@ -48,7 +48,7 @@ fi
 ## end install_skopos
 E
 else
-  echo "Skipping addition to $BASHRC. I think it exists already."
+	echo "Skipping addition to $BASHRC. I think it exists already."
 fi
 
 echo "Installation is complete. You should logout and log back in, or source your $BASHRC"
